### ISSUE TITLE
OutOfMemoryException while calculating hash

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#105]
```
7>MSBUILD : error : Fody: An unhandled exception occurred:
7>MSBUILD : error : Exception:
7>MSBUILD : error : Exception of type 'System.OutOfMemoryException' was thrown.
7>MSBUILD : error : StackTrace:
7>MSBUILD : error :    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
7>MSBUILD : error :    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
7>MSBUILD : error :    at ModuleWeaver.CalculateHash() in c:\TeamCity\buildAgent\work\c596b706194e070d\Fody\HashCalculator.cs:line 13
7>MSBUILD : error :    at ModuleWeaver.Execute() in c:\TeamCity\buildAgent\work\c596b706194e070d\Fody\ModuleWeaver.cs:line 33
7>MSBUILD : error :    at lambda_method(Closure , Object )
7>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 135
7>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 53
7>MSBUILD : error : Source:
7>MSBUILD : error : System.Core
7>MSBUILD : error : TargetSite:
7>MSBUILD : error : Void .ctor(System.Collections.Generic.IEnumerable`1[TElement])
7>MSBUILD : error :
```

Looking into details. If I find more info, I will let you know here.

**Comment by distantcam** [comment]
@GeertvanHorrik Did you get any more info about this?

**Comment by GeertvanHorrik** [comment]
No, sorry, I forgot about this one. Seems it was caused by a combination of Costura and LoadAssembliesOnStartup. We can close this one.
