### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by krispenner** [Fody/Costura#154]
Hi,

Is there a limit to the size of an EXE assembly?  I have a referenced assembly with an embedded zip file as a resource in it, the zip file is 200MB so the assembly is 200MB.

I am then using Fody Costura to embed this large assembly and about 18 other referenced assemblies into my single EXE assembly. The end result is an EXE assembly that is about 210MB.  However, 2 out of 3 times I get the below OutOfMemoryException error thrown during compilation, while 1 out of 3 tries the assembly embedding works.  I don't change anything, just recompile and eventually it may work.  Any suggestions or known reasons why this would fail?

Project at 'C:\Dev\MyProject\MyProject.csproj' failed to build. Error : Fody: An unhandled exception occurred:
Exception:
Exception of type 'System.OutOfMemoryException' was thrown.
StackTrace:
   at Mono.Cecil.PE.ByteBuffer.Grow(Int32 desired)
   at Mono.Cecil.PE.ByteBuffer.WriteBytes(Byte[] bytes)
   at Mono.Cecil.MetadataBuilder.AddResources()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 65
Source:
Mono.Cecil
TargetSite:
Void Grow(Int32)
 in C:\Dev\MyProject\MyProject.csproj on line 0 at column 0.

Thanks!
Kris

**Comment by bigretromike** [comment]
same problem. but after closing all apps and restarting VS it went thru.

**Comment by distantcam** [comment]
This should be fixed as of 1.4.

**Comment by ademgashi** [comment]
I am running only visual studio and everything closed, tried restarting vs and pc but without luck

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Exception of type 'System.OutOfMemoryException' was thrown.
StackTrace:
   at Mono.Cecil.PE.ByteBuffer.Grow(Int32 desired)
   at Mono.Cecil.PE.ByteBuffer.WriteBytes(Byte[] bytes)
   at Mono.Cecil.MetadataBuilder.AddResources()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__1_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
Source:
Mono.Cecil
TargetSite:
Void Grow(Int32)

**Comment by SimonCropp** [comment]
@ademgashi you are using a version that is over a year old. update to the current version and if the problem still persists, raise a new issue
