### ISSUE TITLE
Visual Studio 2017 RC cannot find Microsoft.Build.Framework

### ISSUE THREAD

**Issue by clmcgrath** [Fody/Costura#173]
Building a project unmodified in latest RC build throws an exception complaining that it can't find Microsoft build framework

**Comment by clmcgrath** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:

Server stack trace: 
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IInnerWeaver.set_Logger(ILogger value)
   at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
   at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
   at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
Source:
mscorlib
TargetSite:
Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:	DiagnosticsSharp.Runner			

```

**Comment by distantcam** [comment]
I suspect this might be a Fody problem.

**Comment by clmcgrath** [comment]
will cross post this to the main repo until we can determine a resolution

**Comment by clmcgrath** [comment]
I did a full uninstall then reinstall of the fody and costura  package and restarted windows and it finally seems to be working now (package restore did not fix it). i had to restart windows as something was hard locking the fody package folder, i also installed the multi targeting pack so not sure if that was what fixed it or not... regardless the problem seems to be fixed now. will close the issue as this seems to be resolved

**Comment by airbreather** [comment]
I had this same problem for a bit.  I think the problem is the NuGet Costura.Fody package allows a lower version of Fody than the earliest version that will work.

Repro (1m25s): https://youtu.be/zXvP3TzZxII
