### ISSUE TITLE
Costura packs itself in the output exe when using PackageReference

### ISSUE THREAD

**Issue by bramborman** [Fody/Costura#222]
I just upgraded my console app to `PackageReference`  however in the Output window I noticed that Costura packs itself in the output exe. Here's the log:

```
1>    Fody: Fody (version 2.0.0.0) Executing
1>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
1>      Fody/Costura:   	Embedding 'C:\Users\marian\.nuget\packages\Costura.Fody\1.6.2\lib\dotnet\Costura.dll'
1>      Fody/Costura:   	Embedding 'C:\Users\marian\.nuget\packages\Costura.Fody\1.6.2\lib\dotnet\Costura.pdb'
1>      Fody/Costura:   	Embedding 'C:\Users\marian\.nuget\packages\Newtonsoft.Json\10.0.3\lib\net45\Newtonsoft.Json.dll'
```

So I downloaded previous commit, that uses `packages.config` and there it doesn't pack itself in the exe:

```
1>    Fody: Fody (version 2.0.0.0) Executing
1>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
1>      Fody/Costura:   	Embedding 'C:\Users\marian\Documents\GitHub\SnakeTheResurrection\packages\Newtonsoft.Json.10.0.3\lib\net45\Newtonsoft.Json.dll'
```

**Comment by Lakritzator** [comment]
Good point, I just came across the same "issue".

I added ExcludeAssets like this:

```
	<PackageReference Include="Costura.Fody" Version="1.6.2">
		<ExcludeAssets>runtime</ExcludeAssets>
	</PackageReference>
```

Now costura.dll is not embedded, but still I get an exception when starting the exe:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=An item with the same key has already been added
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Costura.AssemblyLoader..cctor() in ... \obj\Debug\ILTemplate.cs:line 8
```
Which is similar to #182, but should already be fixed.

**Comment by Lakritzator** [comment]
Actually the like number doesn't make sense...?
This would be at the line where nullCacheLock is defined.
```
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading;

static class ILTemplate
{
    static readonly object nullCacheLock = new object();

```

**Comment by n00bje** [comment]
Not sure if it helps, but here's a stacktrace:

  ```
  at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
  at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
  at Costura.AssemblyLoader..cctor() in C:\src\***\***************************\****\*******\***************\obj\Debug\ILTemplate.cs:line 8
  ```

**Comment by Lakritzator** [comment]
I tried this with another solution and made sure there are no cache settings. Also added Costura to the ExcludeAssemblies of it's own configuration, the problem is still there.

**Comment by SimonCropp** [comment]
happy to take a PR that fixes this

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue

**Comment by moh-hassan** [comment]
I reference Costura.Fody in this way:

       <ItemGroup>
        <PackageReference Include="Costura.Fody" Version="3.3.3">
        <PrivateAssets>All</PrivateAssets>
      </PackageReference>
    </ItemGroup>
