### ISSUE TITLE
Cannot build with Fody v2.4.1

### ISSUE THREAD

**Issue by lwchkg** [Fody/Costura#258]
Please see the build log below:

```
1>------ Rebuild All started: Project: Nibbles_VBGraphics, Configuration: Release Any CPU ------
1>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
1>    Fody: Fody (version 2.4.1.0) Executing
1>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Object reference not set to an instance of an object.
1>MSBUILD : error : Type:
1>MSBUILD : error : System.NullReferenceException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver.FindMsCoreReferences() in C:\projects\costura\src\Costura\MsCoreReferenceFinder.cs:line 13
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 29
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
1>MSBUILD : error :    at InnerWeaver.Execute()
1>MSBUILD : error : Source:
1>MSBUILD : error : Costura.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void FindMsCoreReferences()
1>MSBUILD : error : 
1>    Fody:   Finished Fody 236ms.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by GregObleshchuk** [comment]
I have this issue as well

**Comment by KennethVerburg** [comment]
Same here (with Rebuild in VS2017 or msbuild outside VS2017), using Costura 1.6.2.0 in a WPF 4.5.1 solution. When reverting back tot Fody 2.2.1 the issue goes away.

Error		Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object.
Type:
System.NullReferenceException
StackTrace:
   at ModuleWeaver.FindMsCoreReferences() in C:\projects\costura\src\Costura\MsCoreReferenceFinder.cs:line 13
   at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 29
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
Costura.Fody
TargetSite:
Void FindMsCoreReferences()	<ApplicationName>

**Comment by VBobCat** [comment]
Same error in same circumstances

**Comment by SimonCropp** [comment]
Can someone upload a repro?

**Comment by Xathz** [comment]
I just ran into this issue myself. It builds just fine on my machine (Windows 10) but on [Travis it fails](https://travis-ci.org/Xathz/Drag-and-Drop-Backup/builds/351830014#L1962). I have yet to try a version roll back.

Fody v2.4.5
Costura v1.6.2
[Project with the issue](https://github.com/Xathz/Drag-and-Drop-Backup)

**Comment by lwchkg** [comment]
https://github.com/lwchkg/Nibbles_VBGraphics : This one is being worked on recently.
https://github.com/lwchkg/DotNetEditor : Not being worked on this year, but it also use Costura.

Both fails building with new Fody on my Win10 machine, but working with the version of Fody listed there.

**Comment by Xathz** [comment]
Not sure if this helps, but here's the output from Fody. Tried another Windows 10 machine, still works, just fails on Travis.

<details><summary><b>Project builds successfully</b> (click)</summary><p>

https://api.travis-ci.org/v3/job/339617251/log.txt

```
Fody: Fody (version 2.2.1.0) Executing
Fody: ProjectDirectory: '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/'.
Fody: AssemblyPath: '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.exe'
Fody: Found path to weavers file '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/FodyWeavers.xml'.
Fody: SolutionDirectory path is '/home/travis/build/Xathz/Drag-and-Drop-Backup/'
Fody: Finding weavers
Fody: No PackageDefinitions
Fody: Skipped scanning '/home/travis/build/Xathz/Drag-and-Drop-Backup/Packages' for weavers since it doesn't exist.
Fody: Could not find packages dir from nuget config.
Fody: SolutionDirectoryPath: /home/travis/build/Xathz/Drag-and-Drop-Backup/
Fody: Adding weaver dlls from '/home/travis/build/Xathz/Drag-and-Drop-Backup/packages'.
Fody: Fody weaver file added '/home/travis/build/Xathz/Drag-and-Drop-Backup/packages/Costura.Fody.1.6.2/Costura.Fody.dll'
Fody: SolutionDirectoryPath: /home/travis/build/Xathz/Drag-and-Drop-Backup/
Fody: Skipped scanning '/home/travis/build/Xathz/Drag-and-Drop-Backup/Tools' for weavers since it doesn't exist.
Fody: No Weaver project file found.
Fody: Finished finding weavers 43ms
Fody: Creating a new AppDomain
Fody: Reference count=14
Fody: Found debug symbols at '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.pdb'.
Fody: Weaver '/home/travis/build/Xathz/Drag-and-Drop-Backup/packages/Costura.Fody.1.6.2/Costura.Fody.dll'.
Fody:   Initializing weaver
Fody:   Loading '/home/travis/build/Xathz/Drag-and-Drop-Backup/packages/Costura.Fody.1.6.2/Costura.Fody.dll' from disk.
Fody/Costura:   Executing Weaver 
Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
Fody/Costura:   	Embedding '/home/travis/build/Xathz/Drag-and-Drop-Backup/packages/Newtonsoft.Json.10.0.3/lib/net45/Newtonsoft.Json.dll'
Fody/Costura:   Finished 'Costura' in 372ms 
Fody:   Adding weaving info
Fody:   Finished in 2ms 
Fody:   Writing assembly to '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.exe'.
Fody:   Finished writing assembly 175ms.
Fody:   Finished Fody 1183ms.
Target _CopyAppConfigFile:
Copying file from '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/App.config' to '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/bin/Release/DragAndDropBackup.exe.config'
Target DeployOutputFiles:
Copying file from '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.pdb' to '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/bin/Release/DragAndDropBackup.pdb'
Copying file from '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.exe' to '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/bin/Release/DragAndDropBackup.exe'
Target FodyVerifyTarget:
Fody: Found path to weavers file '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/FodyWeavers.xml'.
Fody:   Skipped Verifying assembly since it is disabled in configuration
Fody:   Finished verification in 3ms.
Done building project "/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/Drag and Drop Backup.csproj".
Done building project "/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup.sln".
```

</p></details>
<div class="paragraph"><p></p></div>
<details><summary><b>Project build fails</b> (click)</summary><p>

https://api.travis-ci.org/v3/job/352005960/log.txt

```
Fody: Fody (version 2.4.6.0) Executing
Fody: ProjectDirectory: '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/'.
Fody: AssemblyPath: '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/obj/Release/DragAndDropBackup.exe'
Fody: Found path to weavers file '/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/FodyWeavers.xml'.
Fody: SolutionDirectory path is '/home/travis/build/Xathz/Drag-and-Drop-Backup/'
Fody: Finding weavers
Fody: FindAddinDirectories:
Fody:   No PackageDefinitions
Fody:   Skipped SolutionDir/Packages convention '/home/travis/build/Xathz/Drag-and-Drop-Backup/Packages' since it doesn't exist.
Fody:   Skipped directory from Nuget Config since it could not be derived.
Fody:   Scanning the MsBuildThisFileDirectory parent: /home/travis/build/Xathz/Drag-and-Drop-Backup/'.
Fody:   Skipped scanning '/home/travis/build/Xathz/Drag-and-Drop-Backup/Tools' since it doesn't exist.
Fody:   Skipped NuGetPackageRoot since it is not defined.
Fody: No Weaver project file found.
: error : Fody: Could not find a weaver named 'Costura'.
If you have nuget package restore turned on you probably need to do a build to download the weavers.
Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate NuGet package.
This url may provide more information http://nuget.org/packages/Costura.Fody/ .
Fody:   Finished Fody 88ms.
Task "Fody.WeavingTask" execution -- FAILED
Done building target "FodyTarget" in project "/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/Drag and Drop Backup.csproj".-- FAILED
Done building project "/home/travis/build/Xathz/Drag-and-Drop-Backup/DragAndDropBackup/Drag and Drop Backup.csproj".-- FAILED
Task "MSBuild" execution -- FAILED
```

</p></details>
<div class="paragraph"><p></p></div>

Too much changed [between versions](https://github.com/Fody/Fody/compare/2.2.1...2.4.6) for me to look at.

**Comment by SimonCropp** [comment]
can u try version 2
