### ISSUE TITLE
Could not load FodyIsolated.dll, operation not supported

### ISSUE THREAD

**Issue by Foxtrek64** [Fody/Costura#297]
Hello,

I have a console-based installer that I wrote in C# that provides us with the capability to perform unmanaged AV installs on internal systems. To do this, we rely on `Costura.Fody` (version 3.1.0) and `Fody` (version 3.1.3) to embed a git library into the application as a fallback for standard network transfers (some of the devices we install the AV client on do not have access to the local network and therefore download our AV files through a private git repository.)

I recently was asked to make a tweak to the installer to provide some extra capabilities, but upon attempting to build, I receive the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'file:///Z:\Visual Studio 2017\Projects\LANDeskAVInstall\packages\Fody.3.1.3\netclassictask\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Type:
System.IO.FileLoadException
StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at Processor.ExecuteInOwnAssemblyLoadContext()
   at Processor.Inner()
   at Processor.Execute()
Source:
mscorlib
TargetSite:
System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Type:
System.NotSupportedException
StackTrace:	LANDeskAVInstall			
```

I have tried uninstalling and reinstalling the `Costura.Fody` and `Fody` DotNet packages to no avail. Updating `Fody` to the recent `3.1.4` release saw no change either. It should also be noted that I am running Visual Studio as Administrator (both being a local admin and right-click + run as administrator).

The application itself is fairly simple, though because of its nature, I'm not allowed to open-source it. That said, I can share some pieces of it.

Project Layout:
![image](https://user-images.githubusercontent.com/7003081/44175511-08f6a100-a0ac-11e8-8843-f7fa09b7e3d2.png)

`FodyWeavers.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura>
    <Unmanaged32Assemblies>
      git2-1196807
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      git2-1196807
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>
```

Any assistance with this would be greatly appreciated. Management is eager to get this update pushed and it's hard to test and validate when my app won't build.

Thanks in advance!

**Comment by Foxtrek64** [comment]
I can go ahead with uploading the demo code, but I found something that may actually be the cause.

I built a demo project on the local C: drive and it worked fine (after manually installing the Fody nuget package because Costura's dependency wasn't automatically installed), but when building a new demo project on the company share with identical code, I got the same error.

I noticed in the original Stack Trace it mentioning the following:
```
TargetSite:
System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.```

Following this link suggested I add the following to my `App.config` file:
```
<configuration>
   <runtime>
      <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>
```
While adding that line had no result, I do believe this issue is directly related to loading the project from the company share (read "network location") and not from my local drive, which tells me it's a problem with Visual Studio and not Costura.

As such, I'll go ahead and close.

**Comment by SimonCropp** [comment]
yeah building from a network share is not supported https://github.com/Fody/Fody/wiki/BuildingFromANetworkShare
