### ISSUE TITLE
FIPS Compliance

### ISSUE THREAD

**Issue by rhaehnel** [Fody/Costura#300]
Hello,
We are using Costura and it works quite well, however, we've recently started making our products FIPS compliant and Costura is causing us some issues in this regard. Are there any plans to make Costura FIPS compliant? It appears that it's the SHA1 usage that is causing the issue. I am willing to look into this and supply a PR if needed.

thanks.

**Comment by SimonCropp** [comment]
Happy to accept a pr for this

**Comment by nadcraker** [comment]
@rhaehnel Do you have any more detail on what kinds of issues? I'm having a problem where my project that uses Fody won't build. I get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\username\source\repos\ProjectName\packages\Costura.Fody.2.0.1\netclassicweaver\Costura.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Exception has been thrown by the target of an invocation.
Type:
System.Reflection.TargetInvocationException
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at ModuleWeaver.CalculateHash()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
mscorlib
TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
Type:
System.InvalidOperationException
StackTrace:
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
Source:
mscorlib
TargetSite:
Void .ctor()	ProjectName
```

**Comment by nadcraker** [comment]
My assumption is that the use of the MD5 hash is the problem. I don't think MD5 is allowed when Windows is in FIPS mode.

**Comment by rhaehnel** [comment]
agreed, it's the MD5/SHA1. We got a different error as we didn't do the dev on a FIPS machine, but rather, we got the error when we tried to deploy the executable.

**Comment by nadcraker** [comment]
Yeah I know that. My workplace is still using it, however.
