### ISSUE TITLE
Out of memory exception on build

### ISSUE THREAD

**Issue by ademgashi** [Fody/Costura#345]
I have upgraded the Fody and Costura to the latest versions, I am building a .net 3.5 solution that has a big resource file 555mb on it I am getting the following exception.

Fody: An unhandled exception occurred:
Exception:
Exception of type 'System.OutOfMemoryException' was thrown.
Type:
System.OutOfMemoryException
StackTrace:
   at Mono.Cecil.PE.ByteBuffer.Grow(Int32 desired) in C:\projects\cecil\Mono.Cecil.PE\ByteBuffer.cs:line 330
   at Mono.Cecil.PE.ByteBuffer.WriteBytes(Byte[] bytes) in C:\projects\cecil\Mono.Cecil.PE\ByteBuffer.cs:line 276
   at Mono.Cecil.MetadataBuilder.AddResources() in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 1187
   at Mono.Cecil.MetadataBuilder.BuildModule() in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 1033
   at Mono.Cecil.MetadataBuilder.BuildMetadata() in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 1008
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 136
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in C:\projects\cecil\Mono.Cecil\ModuleDefinition.cs:line 958
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 135
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 115
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\projects\cecil\Mono.Cecil\AssemblyWriter.cs:line 79
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in C:\projects\cecil\Mono.Cecil\ModuleDefinition.cs:line 1154
   at InnerWeaver.WriteModule()
   at InnerWeaver.Execute()
Source:
Mono.Cecil
TargetSite:
Void Grow(Int32)

**Comment by SimonCropp** [comment]
Did u read the issue template?
