### ISSUE TITLE
System.ArgumentNullException after upgrading to v5.3

### ISSUE THREAD

**Issue by jonreis** [Fody/Costura#697]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] WPF

## Version of Library
v5.3.
No error in v5.3

I get the following error when upgrading to v5.3. If I downgrade back to v5.2 the issue goes away.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\jonre\.nuget\packages\costura.fody\5.3.0\build\..\netclassicweaver\Costura.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 220
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 111
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Value cannot be null.
Parameter name: type
Type:
System.ArgumentNullException
StackTrace:
   at Mono.Cecil.Mixin.CheckType(Object type) in C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1258
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context) in C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 859
   at ModuleWeaver.Resolve(TypeReference baseType)
   at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies)
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 185
Source:
Mono.Cecil
TargetSite:
Void CheckType(System.Object)	HL7Spy.KeyGenerator

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by jonreis** [comment]
@SimonCropp ok, I will close the issue and consider becoming a Patron.
