### ISSUE TITLE
Confluent.Kafka doesn't get the correct Costura temp path

### ISSUE THREAD

**Issue by rios0rios0** [Fody/Costura#726]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component
`Costura.Fody`

## Version of Library
5.3.0

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Create any app with .NET 4.7;
2. Add `Confluent.Kafka`;
3. Add `Costura.Fody`;
4. Edit the `FodyWeavears.xml` to:
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
    <Unmanaged32Assemblies>
      librdkafka
      librdkafkacpp
      libzstd
      msvcp120
      msvcr120
      zlib
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      librdkafka
      librdkafkacpp
      libzstd
      msvcp120
      msvcr120
      zlib
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>
```
5. Add any library you want, to prove that `Costura` works;
6. Call any method of `Confluent.Kafka`;
7. Run, and get you error:
```
Unhandled Exception: System.InvalidOperationException: Error while loading librdkafka.dll or its dependencies from *current.dir*\librdkafka.dll. Check the directory exists, if not check your deployment process. You can also load the library and its dependencies by yourself before any call to Confluent.Kafka ---> System.ComponentModel.Win32Exception: The specified module could not be found
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Impl.Librdkafka.LoadNetFrameworkDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
   at ActiveDirectory.Infrastructure.Helpers.QueueHelper.<SendMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

## Expected Behavior
I would like that `Confluent.Kafka` to load correctly the library from the path that Costura changed.

## Actual Behavior
`Confluent.Kafka` doesn't know how to search in `Costura.Fody` temp path.

**Important:** I opened an issue inside `Confluent.Kafka` to there staff answer some this question too.
I would like to know where is the main problem. If you could, please, read it too: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1660

**Comment by SimonCropp** [comment]
just to confirm, are you a patron on open collective? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by rios0rios0** [comment]
> just to confirm, are you a patron on open collective? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

All right. Not yet. Give me a second and I'll.

**Comment by rios0rios0** [comment]
@SimonCropp done!
![image](https://user-images.githubusercontent.com/32651906/127069003-fec45260-fb95-4b96-852d-e191b4237693.png)

**Comment by GeertvanHorrik** [comment]
Please check if it's not similarish to this issue:

https://github.com/Fody/Costura/issues/641#issuecomment-766432917

If this is the issue, I think the only way to solve this is to extract / copy the native dll to the correct path.

**Comment by rios0rios0** [comment]
> Please check if it's not similarish to this issue:
> 
> [#641 (comment)](https://github.com/Fody/Costura/issues/641#issuecomment-766432917)
> 
> If this is the issue, I think the only way to solve this is to extract / copy the native dll to the correct path.

No, it's not. Please, read the complete information inside the Confluent.Kafka repository... You can see what I want to say...

**Comment by SimonCropp** [comment]
have you debugged into this to see what paths it is checking

```
private static void LoadNetFrameworkDelegates(string userSpecifiedPath)
{
	string text = userSpecifiedPath;
	if (text == null)
	{
		bool flag = IntPtr.Size == 8;
		string directoryName = Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().GetName().EscapedCodeBase).LocalPath);
		text = Path.Combine(Path.Combine(directoryName, flag ? Path.Combine("librdkafka", "x64") : Path.Combine("librdkafka", "x86")), "librdkafka.dll");
		if (!File.Exists(text))
		{
			text = Path.Combine(Path.Combine(directoryName, flag ? "runtimes\\win-x64\\native" : "runtimes\\win-x86\\native"), "librdkafka.dll");
		}
		if (!File.Exists(text))
		{
			text = Path.Combine(Path.Combine(directoryName, flag ? "x64" : "x86"), "librdkafka.dll");
		}
		if (!File.Exists(text))
		{
			text = Path.Combine(directoryName, "librdkafka.dll");
		}
	}
	if (WindowsNative.LoadLibraryEx(text, IntPtr.Zero, WindowsNative.LoadLibraryFlags.LOAD_WITH_ALTERED_SEARCH_PATH) == IntPtr.Zero)
	{
		Win32Exception innerException = new Win32Exception();
		throw new InvalidOperationException("Error while loading librdkafka.dll or its dependencies from " + text + ". Check the directory exists, if not check your deployment process. You can also load the library and its dependencies by yourself before any call to Confluent.Kafka", innerException);
	}
	if (!SetDelegates(typeof(Confluent.Kafka.Impl.NativeMethods.NativeMethods)))
	{
		throw new DllNotFoundException("Failed to load the librdkafka native library.");
	}
}
```

**Comment by SimonCropp** [comment]
can you also create a stand alone github repository that contains a minimal repro for this issue

**Comment by tom-englert** [comment]
Looking at the Kafka code I think there is nothing much that Costura can do about it. 
The only solution I can see is that Kafka probes to load the native dll without any path first (`WindowsNative.LoadLibraryEx("librdkafka.dll", ...`). This should succeed if the dll is already loaded, e.g. by Costura. If it fails, it should continue with the existing search method.

**Comment by rios0rios0** [comment]
> Looking at the Kafka code I think there is nothing much that Costura can do about it.
> The only solution I can see is that Kafka probes to load the native dll without any path first (`WindowsNative.LoadLibraryEx("librdkafka.dll", ...`). This should succeed if the dll is already loaded, e.g. by Costura. If it fails, it should continue with the existing search method.

I tried to load before. But it doesn't work either. I was using "PreLoadOrder" as I said here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1660.

**Comment by tom-englert** [comment]
@rios0rios0 not just load it before the existing Kafka code - that won't work.
**Change** the Kafka code!

**Comment by tom-englert** [comment]
@rios0rios0 did you try this from your code, before you make any other call to kafka :
```c#
Librdkafka.Initialize("librdkafka.dll")
```
(PreLoadOrder might be important, too.)

**Comment by rios0rios0** [comment]
> @rios0rios0 did you try this from your code, before you make any other call to kafka :
> 
> ```cs
> Librdkafka.Initialize("librdkafka.dll")
> ```
> 
> (PreLoadOrder might be important, too.)

Yes! I tried. But I made this work with the correct temp path of Costura.

**Comment by rios0rios0** [comment]
> @rios0rios0 not just load it before the existing Kafka code - that won't work.
> **Change** the Kafka code!

Doens't make sense I guess...
That's why I created the issue inside the Kafka repository... The confluent team is in charge to analyze this decision.

**Comment by tom-englert** [comment]
> > @rios0rios0 did you try this from your code, before you make any other call to kafka :
> > ```cs
> > Librdkafka.Initialize("librdkafka.dll")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (PreLoadOrder might be important, too.)
> 
> Yes! I tried. But I made this work with the correct temp path of Costura.
Then you did not try **this**

**Comment by rios0rios0** [comment]
> > > @rios0rios0 did you try this from your code, before you make any other call to kafka :
> > > ```cs
> > > Librdkafka.Initialize("librdkafka.dll")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (PreLoadOrder might be important, too.)
> > 
> > 
> > Yes! I tried. But I made this work with the correct temp path of Costura.
> 
> Then you did not try **this**

Friend...
FYI: when I opened this issue, I had already solved the problem with:
```
private static void LoadNativeKafkaLib()
{
  var tmpDirectory = new DirectoryInfo(Path.Combine(Path.GetTempPath(), "Costura"));
  var costuraPath = Path.Combine(tmpDirectory
    .GetDirectories().First().FullName, Environment.Is64BitProcess ? "64" : "32");
  Library.Load(Path.Combine(costuraPath, "librdkafka.dll"));
}
```
As I said here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1660#issue-953287194
"I created a workaround (working successfully) with this idea: https://stackoverflow.com/a/66970630/10746857.".
Then, answering you: yes! I tested with `Librdkafka.Initialize`.

So, the first useful information is: there's no public call directly to `Librdkafka` we need to call: `Confluent.Kafka.Library.Load()`.
This method calls the method already discussed by @SimonCropp. And this method search by a `dll` in the current directory, or in installation directory inside the path of .exe built.

Please, could you help me with a solution without modifying the Kafka code?
Because the Confluent team didn't answer me yet. And I didn't like my workaround as well.

**Comment by tom-englert** [comment]
@rios0rios0 so did you ever try this?
private static void LoadNativeKafkaLib()
{
  Library.Load("librdkafka.dll");
}

**Comment by rios0rios0** [comment]
> @rios0rios0 so did you ever try this?
> ```c#
> private static void LoadNativeKafkaLib()
> {
>   Library.Load("librdkafka.dll");
> }
> ```
> 

Of course my friend.
`Library.Load` doesn't accept only the name, because there's no `dll` in the current path.

**Comment by tom-englert** [comment]
OK, giving up, this guy is not really looking for help.

**Comment by rios0rios0** [comment]
> OK, giving up, this guy is not really looking for help.

I can see your try.
I will upload my code too... I think that I'm doing something wrong if you are correct.
Sorry if you think that I'm not wanting help... I'm trying to explain myself.

**Comment by GeertvanHorrik** [comment]
Maybe we are not understanding the issue correctly and you indeed already tried what we asked you to test. But without code that is really hard to see, so a repro, *preferably as unit test in Costura*, would be amazing.

**Comment by tom-englert** [comment]
When Costura has already loaded the libraries, no path is needed for `LoadLibrary`, just specifying only the file name will simply return the handle of the loaded library.

My guess is that the `PreLoadOrder` is wrong, and Costura did not load all of the libraries sucessfully,

@GeertvanHorrik in Costura `SetDllDirectory` + `LoadLibrary` is used. Using `LoadLibraryEx(..., LOAD_WITH_ALTERED_SEARCH_PATH)` might be the better solution, and `PreLoadOrder` would not be required here.
Any idea why it was done this way?

**Comment by 0xced** [comment]
Does Costura actually automatically load the libraries defined in the `Unmanaged32Assemblies` and `Unmanaged64Assemblies` xml elements of the FodyWeavers.xml configuration?

I have always used embedded resources in `costura32` and `costura64` for native dlls as described on [Native Libraries and PreloadOrder](https://github.com/Fody/Costura/#native-libraries-and-preloadorder). For example, this is how I do it for SQLite:
```xml
<ItemGroup>
    <EmbeddedResource Include="$(PkgSQLitePCLRaw_lib_e_sqlite3)\runtimes\win-x86\native\e_sqlite3.dll">
        <Link>costura32\e_sqlite3.dll</Link>
        <Visible>false</Visible>
    </EmbeddedResource>
    <EmbeddedResource Include="$(PkgSQLitePCLRaw_lib_e_sqlite3)\runtimes\win-x64\native\e_sqlite3.dll">
        <Link>costura64\e_sqlite3.dll</Link>
        <Visible>false</Visible>
    </EmbeddedResource>
    <Content Remove="@(Content)" Condition="'%(Filename)%(Extension)' == 'e_sqlite3.dll'" />
    <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)%(Extension)' == 'e_sqlite3.dll' OR '%(Filename)%(Extension)' == 'SQLitePCLRaw.batteries_v2.dll'" />
</ItemGroup>
```
(You can read the full explanation here: https://stackoverflow.com/questions/63887709/how-to-package-a-single-file-executable-using-the-sqlite-ef-core-database-provid/63887710#63887710)

What's the difference between _unmanaged_ and _native_ dlls?

**Comment by rios0rios0** [comment]
> Maybe we are not understanding the issue correctly and you indeed already tried what we asked you to test. But without code that is really hard to see, so a repro, _preferably as unit test in Costura_, would be amazing.

@tom-englert @GeertvanHorrik 

Sorry about the unit test... I didn't have time to learn how to use Costura in the unit test, to be honest with you...
But if you give me some attention, look here please: https://github.com/rios0rios0/test-kafka-costura
This is a simple project, and you would have the same facility to test as a unit test... And if everything is fine, you'll get this error:

```
Hello World!

Unhandled Exception: System.InvalidOperationException: Error while loading librdkafka.dll or its dependencies from librdkafka.dll. Check the directory exists, if not check your deployment process. You can also load the library and its dependencies by yourself before any call to Confluent.Kafka ---> System.ComponentModel.Win32Exception: The specified module could not be found
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Impl.Librdkafka.LoadNetFrameworkDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at ConsoleApp1.QueueHelper.LoadNativeKafkaLib()
   at ConsoleApp1.QueueHelper.SendMessage(String topic, String message)
   at ConsoleApp1.Program.Main(String[] args)
```

**Comment by tom-englert** [comment]
I don't see the PreLoadOrder

**Comment by rios0rios0** [comment]
> I don't see the PreLoadOrder

I'm sorry, now added. I removed it because it doesn't affect ... The error keeps the same.

**Comment by rios0rios0** [comment]
> Where are all those native dlls?

Confluent.Kafka installs everything... I don't need to add anything... Everything is added... All the dlls are inside the folder of the build if you remove the Costura. Could you clone and run?

**Comment by tom-englert** [comment]
The PreLoadOrder is definitely wrong

**Comment by rios0rios0** [comment]
> The PreLoadOrder is definitely wrong

What is the correct way to do it? Could you provide me?

**Comment by 0xced** [comment]
There are many things at play in this scenario. You can find a working solution for both 32-bit and 64-bit systems in my [embed-native-dlls](https://github.com/0xced/test-kafka-costura/tree/embed-native-dlls) branch. All the native dlls are embedded in the single executable and automatically loaded at runtime by Costura but you still need to call `Confluent.Kafka.Library.Load` with the path where the native `librdkafka` dll was extracted.

The missing pieces were:
1. `CreateTemporaryAssemblies="true"` in Costura configuration so that native dlls are extracted on disk (required for Confluent.Kafka initialization)
2. Proper `PreloadOrder` so that **all** native dlls are loaded successfully
3. Some MSBuild magic (i.e. target that I named `EmbedLibrdkafkaRedistNativeLibraries`) to prevent native dlls from being copied to the output directory and being embedded in virtual `costura32` and `costura64` directories instead.
4. Use the right path when calling `Confluent.Kafka.Library.Load` (was impossible without CreateTemporaryAssemblies="true") to properly initialize Confluent.Kafka.

In addition, I have
* Added `<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>` and `<GenerateSupportedRuntime>false</GenerateSupportedRuntime>` to prevent `ConsoleApp1.exe.config` from being generated. (Binding redirects are not needed thanks to Costura)
* Set `<DebugType>embedded</DebugType>` to embed the pdb inside the exe instead of having it in a separate file
* Used `<PlatformTarget>AnyCPU</PlatformTarget>` so that the app runs in 64-bit by default

**Comment by tom-englert** [comment]
> 3. Use the right path when calling `Confluent.Kafka.Library.Load`.

That is not really needed; you can also omit `CreateTemporaryAssemblies`:

https://github.com/tom-englert/test-kafka-costura/blob/18a4d9fdb02a0c38c4e781b3031c9b244cca40ae/Program.cs#L8-L13:
```c#
    private static void Main(string[] args)
    {
      // you can pass ANY valid library here, it's only important that kafka runs it's internal setup :-)
      Confluent.Kafka.Library.Load("kernel32.dll");

      QueueHelper....
```

QED

**Comment by 0xced** [comment]
> The important part is the correct PreloadOrder!

Yes, you're absolutely right! I have updated my branch by removing `CreateTemporaryAssemblies="true"` and just load `kernel32.dll` to make Confluent.Kafka initialization process happy.

Also, the MSBuild tricks to properly embed 32 **and 64** bits dlls are a key part to have a working single executable.

**Comment by tom-englert** [comment]
> Also, the MSBuild tricks to properly embed 32 and 64 bits dlls are a key part to have a working single executable.

of course this is a major key part :+1:; didn't realize the problem started so low level.

**Comment by 0xced** [comment]
And for the sake of completeness, here's the dependency graph between the native dlls (that I drew with the help of the [Dependencies](https://github.com/lucasg/Dependencies) app and [Monodraw](https://monodraw.helftone.com))

A → B means A depends on B

This explains why the preload order must be `msvcp120|msvcr120|zlib|libzstd|librdkafka|librdkafkacpp` because libraries which have dependents must be loaded first. `msvcp120` and `msvcr120` may be excluded as they should be part of the system, but I'm not 100% sure about it. Maybe I have them on my system because I have installed developer tools.
```
          ┌─────────────────┐                 ┌──────────────┐
          │                 │                 │              │
          │  librdkafkacpp  │────────┬───────▶│   msvcp120   │
          │                 │        │        │              │
          └─────────────────┘        │        └──────────────┘
                   │                 │                        
                   ▼                 │                        
          ┌─────────────────┐        │        ┌──────────────┐
          │                 │        │        │              │
       ┌──│   librdkafka    │──┐     └───────▶│   msvcr120   │
       │  │                 │  │              │              │
       │  └─────────────────┘  │              └──────────────┘
       ▼                       ▼                      ▲       
┌─────────────┐        ┌──────────────┐               │       
│             │        │              │               │       
│   libzstd   │        │     zlib     │───────────────┘       
│             │        │              │                       
└─────────────┘        └──────────────┘                       
```

**Comment by tom-englert** [comment]
msvc*.dll come with the "Microsoft Visual C++ ???? Redistributable" - so they might not be present always.

I once used this workaround to ensure these get not loaded by Costura if they are already present:

FodyWeavers.xml
```xml
 <Costura LoadAtModuleInit="false" ...>
```
Source code:
```c#
// Try to pre-load runtime from system directory, if it's already installed there.
NativeMethods.LoadLibrary("vcruntime140.dll");
if (IntPtr.Size == 4)
    NativeMethods.LoadLibrary("msvcp140.dll");

CosturaUtility.Initialize();
```

**Comment by rios0rios0** [comment]
Thank you, guys. So much!

Only for me understood completely, please:

1 - I need to do all these modifications: https://github.com/0xced/test-kafka-costura/commit/5110321f267a1a0a24ce7b99866e47d4102b451d#diff-666723a92bcb63d993a4b120ac1d4cea92743bc83aa8c8d95b6cf4c9aea4aae6 ?! Right?! I didn't understand completely this part.

2 - I need to do this here too: https://github.com/0xced/test-kafka-costura/commit/5110321f267a1a0a24ce7b99866e47d4102b451d#diff-c8869393600f488c197a707f2f471f46e05670280792fc8039737c759643d62d. I understood why... Ok, no problem.

3 -  And here: https://github.com/tom-englert/test-kafka-costura/blob/18a4d9fdb02a0c38c4e781b3031c9b244cca40ae/Program.cs#L11. Could I call only the Kafka DLL without any path? Or do I need to call with the complete path as here: https://github.com/0xced/test-kafka-costura/commit/5110321f267a1a0a24ce7b99866e47d4102b451d#diff-0b69b473fe937040615d69f606751f61ddbc2e3a1849360ff2456c22afe88c0bR10 ?

**Comment by tom-englert** [comment]
Just use this:
https://github.com/tom-englert/test-kafka-costura/tree/embed-native-dlls

**Comment by GeertvanHorrik** [comment]
@tom-englert did a great job with the PR. It has been approved and a first alpha (5.5.0-alpha.68) is being released to NuGet right now.

@rios0rios0 could you please test this version?

**Comment by rios0rios0** [comment]
> @tom-englert did a great job with the PR. It has been approved and a first alpha (5.5.0-alpha.68) is being released to NuGet right now.
> 
> @rios0rios0 could you please test this version?

@GeertvanHorrik I really would like to understand what is going here...
With this new version, do I need to do all those things listed in my comment?
I asked about some explanation, but the answer was "just do it"...

Could you say some explanation for me? I would like to learn with this process too...

**Comment by tom-englert** [comment]
@rios0rios0 with the new version you can omit the `PreloadOrder`, so the only thing left is to properly embed the native libraries, as shown in the sample by @0xced

**Comment by rios0rios0** [comment]
> @rios0rios0 with the new version you can omit the `PreloadOrder`, so the only thing left is to properly embed the native libraries, as shown in the sample by @0xced

I did... I merged the @0xced PR and removed the **PreloadOrder** from XML. Now I have:
```
Unhandled Exception: System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.Librdkafka.LoadNetFrameworkDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at ConsoleApp1.Program.Main(String[] args) in /home/rios0rios0/Development/github.com/rios0rios0/test-kafka-costura/Program.cs:line 9
 ```

**Comment by tom-englert** [comment]
@rios0rios0 you can omit the `PreloadOrder` as soon as you use the Costura version that supports it!

**Comment by GeertvanHorrik** [comment]
@rios0rios0 what is the version of Costura you are using (e.g. what's in your csproj)?

**Comment by rios0rios0** [comment]
Working guys... I'm sorry, my **NuGet** was disabled to pre-releases. How can we conclude this?
I tested here and is not possible to work without configuration inside the **csproj** (the config made by @0xced to embed the libraries... I just didn't understand how he knew how to do that, wihout any help of interface... Great job!).
And is possible to change the **dll** from `Confluent.Kafka.Library.Load` to **librdkafka** without problems...

**Comment by GeertvanHorrik** [comment]
I think that we can release this as stable. @tom-englert you agree that we can release this and the other PR you did?

**Comment by tom-englert** [comment]
:+1:

**Comment by GeertvanHorrik** [comment]
Stable version is being deployed right now. Please let us know if any other issues arise.

Special thanks to @tom-englert for fixing this!

**Comment by tom-englert** [comment]
... and to @0xced for the msbuild part!
